[package]
name = "groth16-usage"
version = "0.1.0"
edition = "2024"

[dependencies]
icicle-snark = { path = "../../" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "rsa_benchmark"
harness = false

[[bench]]
name = "400k_benchmark"
harness = false

[[bench]]
name = "1600k_benchmark"
harness = false